### ISSUE TITLE
What font was used in creating the Blipshift Title Logo (title.png)?

### ISSUE THREAD

**Issue by BodhiPeace** [wardsky/blipshift#1]
@wardsky,

Do you remember what font was used for the "blipshift" title?
This is needed to make new text images that match that style.

**Comment by wardsky** [comment]
Actually I made the graphics myself, based on this logo:
![tape world](http://www.trademarkia.com/logo-images/record-town/tape-world-73791266.jpg)
I've added the vector file (under '/assets/') in case that's any use to you.

**Comment by BodhiPeace** [comment]
@wardsky 
Thanks, that's good info to have for any future graphics.

I looked at the file and it looks like it doesn't have any text? It just has the ball and the target.

**Comment by wardsky** [comment]
They're in there, just outside the main crop area.  Try opening it in a vector editor (e.g., Inkscape).

**Comment by BodhiPeace** [comment]
Again, I'm glad you could post the source file. I was able to open it in Inkscape. I like the look of the game and hadn't realized it was all vector graphics.
